version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: client.dockerfile
    environment:
      - PORT=3000
      - PUBLIC_API_URL=http://127.0.0.1:8080
    ports:
      - 5173:3000
    networks:
      - fullstack-docker

  server:
    build:
      context: ./server
      dockerfile: backend.dockerfile
    ports:
      - 8080:8080
    networks:
      - fullstack-docker

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    ports:
      - 80:80

networks:
  fullstack-docker:
    driver: bridge
