version: '3'
services:
  fullstack-docker-be:
    build:
      context: ./server
      dockerfile: backend.dockerfile
    ports:
      - 8080:8080
  # fullstack-docker-fe:
  #   build:
  #     context: ./client
  #     dockerfile: client.dockerfile
  #   environment:
  #     - PORT=3000
  #     - PUBLIC_API_URL=http://fullstack-docker-be:8080
  #   ports:
  #     - 3000:3000